service: resume-api
provider:
  name: aws
  runtime: python3.7
  region: eu-central-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  get_resume:
    handler: handler.get_resume
    events:
      - http:
          path: resume
          method: get

plugins:
  - serverless-python-requirements