service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1

functions:
  lambda_function:
    handler: lambda_function/lambda_handler.lambda_handler
    timeout: 60 # seconds
    memorySize: 128 # mb
